In [16]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from tensorflow import keras


In [17]:

training_portion = .80  # Use 80% of data for training, 20% for testing
max_words = 1000        #Max words in text input

data = pd.read_csv('testdata1.csv')

#print out first 5 rows of generated claims so you can see what data looks like
print(data.head())

train_size = int(len(data) * training_portion)

def train_test_split(data, train_size):
    train = data[:train_size]
    test = data[train_size:]
    return train, test

train_cat, test_cat = train_test_split(data.iloc[:,1], train_size)  # label data is second column
train_text, test_text = train_test_split(data.iloc[:,0], train_size)  # text data is first column

tokenize = Tokenizer(num_words=max_words, char_level=False)
tokenize.fit_on_texts(train_text) # fit tokenizer to our training text data

#x_train and x_test are the vectorization of the text data (which is a claim)
x_train = tokenize.texts_to_matrix(train_text)

#following print statement shows some rows in the newly created matrix
print(x_train)
x_test = tokenize.texts_to_matrix(test_text)



  Have to cycle the ignition button at least twice before my car starts.  \
0       I tried starting my car but it doesn't work.                       
1              I can't put gas in my steering wheel.                       
2  My car makes a sputtering noise and does not t...                       
3  Exhaust has a lot of black smoke and acrid smell.                       
4           There is a lag when I open my rear trunk                       

   starter  
0  starter  
1    other  
2  starter  
3    other  
4    other  
[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [18]:
# Use sklearn utility to convert label strings to numbered index
encoder = LabelEncoder()  
encoder.fit(train_cat)

#convert label strings to numbers
y_train = encoder.transform(train_cat)
y_test = encoder.transform(test_cat)

#for each row in the data, each entry represents the value of the label
print(y_train)

# for example:  [2 1 1 2 1 1 0 ...  which corresponds to starter, other, other, starter, other, other, brakes ...

[2 1 2 1 1 0 0 0 1 1 0 1 0 2 1 2 1 1 0 2 1 2 0 1 1 1 1 0 2 1 0 2 2 1 0 2 1
 1 1 0 1 0 1 0 0 1 1 0 0 1 0 0 1 0 0 1 1 0 0 0 1 2 1 2 1 0 0 1 1 1 1 1 1 2
 0 1 0 1 1 2 1 0 0 0 0 1 2 1 1 1 1 2 2 1 2 0 1 0 2 1 2 1 1 2 1 1 1 2 0 1 1
 1 0 0 1 0 1 1 2 0 0 1 2 0 1 1 0 1 1 1 2 0 0 0 2 2 0 0 2 2 1 1 0 0 2 1 0 0
 0 1 2 2 0 2 0 1 2 2 2 2 1 1 0 1 1 2 0 1 2 0 1 2 1 1 0 0 1 1 1 2 1 1 0 1 0
 2 2 0 2 1 2 1 2 0 1 1 0 0 1 1 2 1 1 0 0 1 2 2 1 1 1 2 0 2 2 1 1 2 1 0 1 2
 1 0 2 1 1 0 1 1 1 2 1 0 1 1 1 2 2 2 1 1 1 1 1 2 0 0 2 0 1 2 2 2 1 1 2 2 1
 1 1 2 2 1 2 2 1 1 1 1 1 2 2 1 1 1 0 0 1 1 0 1 0 1 1 0 2 1 2 2 1 1 2 2 1 1
 0 1 1 2 1 1 2 2 0 0 0 2 0 1 1 1 1 2 1 1 1 0 1 0 0 2 1 2 2 2 0 2 0 1 0 0 1
 1 1 0 2 0 0 1 2 1 2 1 1 1 2 1 1 0 1 1 0 0 2 2 1 1 1 2 1 0 1 2 0 1 0 1 1 2
 2 1 1 1 0 1 0 1 1 1 0 0 0 1 1 0 1 1 1 2 1 2 2 1 0 1 1 1 1 1 2 1 1 0 2 1 1
 1 1 1 1 0 1 2 0 0 1 2 1 1 1 1 1 1 1 2 0 0 2 2 0 0 1 2 0 1 1 0 2 2 1 0 2 1
 2 1 0 1 0 1 1 0 2 0 1 2 2 1 0 1 1 0 1 2 1 0 0 1 2 1 2 0 2 1 1 1 1 2 1 0 1
 1 1 1 1 1 1 1 0 1 2 1 2 

In [19]:
# Converts the labels to a one-hot representation

num_classes = len(set(y_train))  # set() creates a unique set of objects
#num_classes = np.max(y_train) + 1
y_train = to_categorical(y_train, num_classes)  #one hot encoding replaces the column of labels whose (values are 0 or 1 or 2)
# with 3 columns each representing 1 label value.  For example, the label 'other' is replaced by the vector 0 1 0, the label 'starter'
#is replaced by the vector 0 0 1, the label 'brakes' is replaced by the vector 1 0 0
y_test = to_categorical(y_test, num_classes)

# Inspect the dimenstions of our training and test data
print('x_train shape:', x_train.shape)
print('x_test shape:', x_test.shape)
print('y_train shape:', y_train.shape)
print('y_test shape:', y_test.shape)

#one hot encoding
#y_train shape: (159, 3)  159 rows, 3 columns
#y_test shape: (40, 3)  40 rows, 3 columns

x_train shape: (799, 1000)
x_test shape: (200, 1000)
y_train shape: (799, 3)
y_test shape: (200, 3)


In [20]:
# Build the model
layers = keras.layers
models = keras.models
model = models.Sequential()
model.add(layers.Dense(512, input_shape=(max_words,), activation='relu'))  # Hidden layer with 512 nodes
model.add(layers.Dense(num_classes, activation='softmax'))

#relu, softmax, categorical_crossentropy are telling the model how to do some internal calculations
#softmax is telling the model to calculate probabilities for each category in each document.  If you only had yes, or no you would use sigmoid instead of
#softmax.

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
batch_size = 32
epochs = 2
history = model.fit(x_train, y_train,       # The variable, history, is normally used to plot learning curves.  fit calculates the weights in the model
                    batch_size=batch_size,  # batch_size tells the internal calculations how many rows to process at one time
                    epochs=epochs,          # epochs is the number of times the model calculations will pass through the entire data
                    verbose=1,
                    validation_split=0.1)

score = model.evaluate(x_test, y_test,       #evaluate compares the model predictions with the actual known test values
                       batch_size=batch_size, verbose=1)
print('Test loss:', score[0])
print('Test accuracy:', score[1])



Epoch 1/2
23/23 [==============================] - 0s 7ms/step - loss: 0.9611 - accuracy: 0.5519 - val_loss: 0.5285 - val_accuracy: 0.9875
Epoch 2/2
7/7 [==============================] - 0s 1ms/step - loss: 0.2464 - accuracy: 0.9550
Test loss: 0.2463839203119278
Test accuracy: 0.9549999833106995


In [24]:
# Here's how to generate a prediction on individual examples
text_labels = encoder.classes_   #ndarray of output values (labels or classes)  e.g. other, brakes, starter

# Examine first 10 test samples of 445
for i in range(len(test_cat)):
    temp = x_test[i]
    prediction = model.predict(np.array([x_test[i]]))
    predicted_label = text_labels[np.argmax(prediction)]  #predicted class
    #print(test_text.iloc[i][:50], "...")                # 50 char sample of text
    #print('Actual label:' + test_cat.iloc[i])
    #print("Predicted label: " + predicted_label + "\n")

#test our model by inputing a new user claim =============   
#print('================================  ENTER TEST PHRASE ====================================')
#single_test_text = 'press brake pedal and car wont stop'  #text has to be a document, the brackets make it a document
single_test_text = 'turn key over and hear a clicking sound' 
#single_test_text = 'there is fluid leaking from the engine' 

#print("Entered text: " + str(single_test_text) + "\n")

#text_as_nparray = np.array([single_test_text])
text_as_series = pd.Series(single_test_text)  #data conversions

single_x_test = tokenize.texts_to_matrix(text_as_series)
single_prediction = model.predict(np.array([single_x_test]))
single_predicted_label = text_labels[np.argmax(single_prediction)]  #maps index of the prediction to the test labels array e.g. brakes
#print("Predicted label: " + single_predicted_label + "\n")

#======================================
#test predication function
#======================================
#print('=====================test prediction function==================================')

def predict(single_test_text):
    text_as_series = pd.Series(single_test_text) #do a data conversion
    single_x_test = tokenize.texts_to_matrix(text_as_series)
    single_prediction = model.predict(np.array([single_x_test]))
    single_predicted_label = text_labels[np.argmax(single_prediction)]  #maps index of the prediction to the test labels array e.g. brakes
    #return {'prediction': license_plate_string}
    return {'predication': single_predicted_label}

prediction = predict(single_test_text)  #call the prediction function

print('returned prediction: ' + str(prediction))

returned prediction: {'predication': 'starter'}


In [25]:
prediction = predict('there is a pool of liquid under the car')
print(prediction)

{'predication': 'other'}
